#https://strimzi.io/docs/operators/latest/full/deploying.html#deploying-the-topic-operator-standalone-str
image: quay.io/strimzi/operator
imageTag: 0.28.0
imagePullPolicy: IfNotPresent

# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: [kafka]
watchAnyNamespace: false

kafka:
  bootstrapServers:
    - kafka-1-headless.kafka.svc.cluster.local:9092
  tls:
    enabled: false

zookeeper:
  servers:
    - kafka-zookeeper.kafka.svc.cluster.local:2181

resourceSelectorLabels:
  - cluster=rts-kafka

resources:
  limits:
    memory: 256Mi
    cpu: 100m
  requests:
    memory: 256Mi
    cpu: 100m

livenessProbe:
  enabled: false
  initialDelaySeconds: 60
  timeoutSeconds: 5
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1

readinessProbe:
  enabled: false
  initialDelaySeconds: 60
  failureThreshold: 6
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1

logLevel: "INFO"

customLogging: |+
  name = TOConfig

  appender.console.type = Console
  appender.console.name = STDOUT
  appender.console.layout.type = PatternLayout
  appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

  rootLogger.level = INFO
  rootLogger.appenderRefs = stdout
  rootLogger.appenderRef.console.ref = STDOUT
  rootLogger.additivity = false

  loggers= io.strimzi.operator.topic.Session,io.strimzi.operator.topic.K8sTopicWatcher,io.vertx.core.impl.BlockedThreadChecker,io.strimzi.operator.topic.TopicOperator

  logger.io.strimzi.operator.topic.TopicOperator.name = io.strimzi.operator.topic.TopicOperator
  logger.io.strimzi.operator.topic.TopicOperator.level = DEBUG

  logger.io.strimzi.operator.topic.Session.name = io.strimzi.operator.topic.Session
  logger.io.strimzi.operator.topic.Session.level = DEBUG
  logger.io.strimzi.operator.topic.K8sTopicWatcher.name = io.strimzi.operator.topic.K8sTopicWatcher
  logger.io.strimzi.operator.topic.K8sTopicWatcher.level = DEBUG

  logger.io.vertx.core.impl.BlockedThreadChecker.name = io.vertx.core.impl.BlockedThreadChecker
  logger.io.vertx.core.impl.BlockedThreadChecker.level = ERROR

