apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "strimzi.fullname" $ }}--{{ .Values.watchNamespace }}-role-binding
  namespace: {{ .Values.watchNamespace }}
  labels: {{- include "strimzi.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: entity-operator-role-binding
roleRef:
  kind: Role
  name: {{ template "strimzi.fullname" . }}-{{ .Values.watchNamespace }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "strimzi.fullname" . }}
    namespace: {{ .Release.Namespace }}