apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "strimzi.fullname" . }}
  labels: {{- include "strimzi.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: service-account
    